services:
    Shopsys\ApiBundle\Controller\:
        resource: '../../Controller/'
        public: false
        autowire: true
        tags: ['controller.service_arguments']

    Shopsys\ApiBundle\Component\HeaderLinks\HeaderLinksTransformer: ~
