shopsys_shop:
    resource: "@ShopsysShopBundle/Resources/config/routing.yml"
    prefix: /

shopsys_framework:
    resource: "@ShopsysFrameworkBundle/Resources/config/routing.yml"

shopsys_api:
    resource: "@ShopsysApiBundle/Resources/config/routing.yml"

oauth2:
    prefix: /api
    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
    
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
